### PR TITLE
Segmentaion template

### PR DESCRIPTION
**Pull request by gt758215**

### CODE REVIEW

**Comment by anastasiia-annata** [comment]
Need to include segmentation_template.rst in index.rst

**Comment by gt758215** [comment]
Change ok~

**Comment by anastasiia-annata** [comment]
"Template" section was refactored, please move "Segmentation template" from index to the "Template"  and mark it as "by request".

**Comment by anastasiia-annata** [comment]
Sorry, I wasn't clear, move the content of segmentation_template.rst to the end of template.rst, now we want to have all template types in one file. 
Also, segmentation template is not included to system by default, so please mark it to by "by request", like this:

Segmentation (by request)
======================

Then you can remove segmentation_template.rst and remove import in index.rst.

**Comment by gt758215** [comment]
Fix in another request to avoid to more unnecessary commit. :)

**Pull request closed without merging**
